### ISSUE TITLE
crash in running example script

### ISSUE THREAD

**Issue by divideby2** [sisl/AdaptiveStressTestingToolbox#10]
python example_runner.py
...
...
...
2019-02-11 14:06:33 | [crosswalk_exp] itr #100 | Computing KL after
2019-02-11 14:06:34 | [crosswalk_exp] itr #100 | Computing loss after
2019-02-11 14:06:34 | [crosswalk_exp] itr #100 | Fitting baseline...
2019-02-11 14:06:34 | [crosswalk_exp] itr #100 | Saving snapshot...
2019-02-11 14:06:35 | [crosswalk_exp] itr #100 | Saved
2019-02-11 14:06:35 | --------------------------  ----------------
2019-02-11 14:06:35 | AverageDiscountedReturn      -9671.75
2019-02-11 14:06:35 | AverageReturn               -15794.1
2019-02-11 14:06:35 | Baseline/ExplainedVariance       0.281897
2019-02-11 14:06:35 | Entropy                          8.48645
2019-02-11 14:06:35 | EnvExecTime                      7.32593
2019-02-11 14:06:35 | Iteration                      100
2019-02-11 14:06:35 | ItrTime                         26.3924
2019-02-11 14:06:35 | MaxReturn                      -83.5971
2019-02-11 14:06:35 | MinReturn                   -37459.8
2019-02-11 14:06:35 | NumTrajs                      1000
2019-02-11 14:06:35 | Perplexity                    4848.63
2019-02-11 14:06:35 | PolicyExecTime                   0.849689
2019-02-11 14:06:35 | ProcessExecTime                  0.330272
2019-02-11 14:06:35 | StdReturn                     8765.39
2019-02-11 14:06:35 | Time                          2490.38
2019-02-11 14:06:35 | lstm_policy/Entropy              0.000526171
2019-02-11 14:06:35 | lstm_policy/KL                   0.0108437
2019-02-11 14:06:35 | lstm_policy/KLBefore             0.0108437
2019-02-11 14:06:35 | lstm_policy/LossAfter          260.074
2019-02-11 14:06:35 | lstm_policy/LossBefore         260.074
2019-02-11 14:06:35 | lstm_policy/dLoss                0
2019-02-11 14:06:35 | --------------------------  ----------------
Traceback (most recent call last):
  File "example_runner.py", line 115, in <module>
    example_save_trials(algo.n_itr, args.log_dir, header, sess, save_every_n=args.snapshot_gap)
  File "/home/divideby2/AdaptiveStressTestingToolbox/Toolbox/example_save_trials.py", line 11, in example_save_trials
    data = joblib.load(path + '/itr_' + str(i) + '.pkl')
  File "/usr/local/anaconda3/lib/python3.6/site-packages/joblib/numpy_pickle.py", line 598, in load
    obj = _unpickle(fobj, filename, mmap_mode)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/joblib/numpy_pickle.py", line 526, in _unpickle
    obj = unpickler.load()
  File "/usr/local/anaconda3/lib/python3.6/pickle.py", line 1050, in load
    dispatch[key[0]](self)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/joblib/numpy_pickle.py", line 339, in load_build
    Unpickler.load_build(self)
  File "/usr/local/anaconda3/lib/python3.6/pickle.py", line 1507, in load_build
    setstate(state)
  File "/usr/local/garage/garage/tf/core/parameterized.py", line 104, in __setstate__
    Serializable.__setstate__(self, d)
  File "/usr/local/garage/garage/core/serializable.py", line 39, in __setstate__
    out = type(self)(*d["__args"], **d["__kwargs"])
  File "/usr/local/garage/garage/tf/policies/gaussian_lstm_policy.py", line 121, in __init__
    use_peepholes=use_peepholes,
  File "/usr/local/garage/garage/tf/core/network.py", line 383, in __init__
    **layer_args)
  File "/usr/local/garage/garage/tf/core/layers.py", line 1595, in __init__
    regularizable=False)
  File "/usr/local/garage/garage/tf/core/layers.py", line 178, in add_param
    param = self.add_param_plain(spec, shape, name, **kwargs)
  File "/usr/local/garage/garage/tf/core/layers.py", line 172, in add_param_plain
    param = create_param(spec, shape, name, **tags)
  File "/usr/local/garage/garage/tf/core/layers.py", line 42, in create_param
    dtype=tf.float32)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py", line 1487, in get_variable
    aggregation=aggregation)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py", line 1237, in get_variable
    aggregation=aggregation)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py", line 540, in get_variable
    aggregation=aggregation)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py", line 492, in _true_getter
    aggregation=aggregation)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py", line 861, in _get_single_variable
    name, "".join(traceback.format_list(tb))))
ValueError: Variable lstm_policy/lstm_mean_network/lstm_layer/lstm_layer/h0 already exists, disallowed. Did you mean to set reuse=True or reuse=tf.AUTO_REUSE in VarScope? Originally defined at:

  File "/usr/local/garage/garage/tf/core/layers.py", line 42, in create_param
    dtype=tf.float32)
  File "/usr/local/garage/garage/tf/core/layers.py", line 172, in add_param_plain
    param = create_param(spec, shape, name, **tags)
  File "/usr/local/garage/garage/tf/core/layers.py", line 178, in add_param
    param = self.add_param_plain(spec, shape, name, **kwargs)

**Comment by mark-koren** [comment]
Significant changes since this bug, will reopen if it can still be reproduced
